version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.7
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
